# Manipulation of data using Python

## Context
The department of transportation publicly released a dataset about the list of flights that occurred in 2015 along with specificities such as delays,
flight time and other information.
This project aims at showing good practices to manipulate data using PYTHON and the most used libraries like PANDAS and NUMPY.

In [3]:
# First, i am going to import the libraries 
import pandas as pd
import numpy as np
import datetime as dt

In [5]:
# The code below, it's focused on drawing insights about flights departing from BOS, JFK, SFO AND LAX.

### Data Preprocessing
I retrieve the data frames from the respective CSV files which have been downloaded from :
https://www.kaggle.com/datasets/usdot/flight-delays

In [8]:
# Retrieving data
flights_datafr_raw = pd.read_csv("C:/Users/TCAMELIDOSARQ6/Desktop/Airports/flights.csv")
airports_datafr_raw = pd.read_csv("C:/Users/TCAMELIDOSARQ6/Desktop/Airports/airports.csv")
airlines_datafr_raw = pd.read_csv("C:/Users/TCAMELIDOSARQ6/Desktop/Airports/airlines.csv")

# view data types and first rows of data frame

flights_datafr_raw.info()

C:\Users\TCAMELIDOSARQ6\AppData\Local\Temp\ipykernel_23732\2590576071.py:2: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  flights_datafr_raw = pd.read_csv("C:/Users/TCAMELIDOSARQ6/Desktop/Airports/flights.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB

In [10]:
display(flights_datafr_raw)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5819074,2015,12,31,4,B6,688,N657JB,LAX,BOS,2359,...,753.0,-26.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819075,2015,12,31,4,B6,745,N828JB,JFK,PSE,2359,...,430.0,-16.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819076,2015,12,31,4,B6,1503,N913JB,JFK,SJU,2359,...,432.0,-8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819077,2015,12,31,4,B6,333,N527JB,MCO,SJU,2359,...,330.0,-10.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5819078,2015,12,31,4,B6,839,N534JB,JFK,BQN,2359,...,442.0,2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# The table above, it has 31 columns and 5.8 millions of rows.
# for our analysis, we are going to use the following dimensions : 
# ORIGIN_AIRPORT, DESTINATION_AIRPORT, YEAR, MONTH, DAY, AIRLINE, FLIGHT_NUMBER, SCHEDULED_DEPARTURE and DEPARTURE_DELAY.
flights_datafr_clean = flights_datafr_raw[['ORIGIN_AIRPORT', 'DESTINATION_AIRPORT','YEAR', 'MONTH', 'DAY', 'AIRLINE', 'FLIGHT_NUMBER',
'SCHEDULED_DEPARTURE', 'DEPARTURE_DELAY']]
display(flights_datafr_clean)

,ORIGIN_AIRPORT,DESTINATION_AIRPORT,YEAR,MONTH,DAY,AIRLINE,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY
0,ANC,SEA,2015,1,1,AS,98,5,-11.0
1,LAX,PBI,2015,1,1,AA,2336,10,-8.0
2,SFO,CLT,2015,1,1,US,840,20,-2.0
3,LAX,MIA,2015,1,1,AA,258,20,-5.0
4,SEA,ANC,2015,1,1,AS,135,25,-1.0
...,...,...,...,...,...,...,...,...,...
5819074,LAX,BOS,2015,12,31,B6,688,2359,-4.0
5819075,JFK,PSE,2015,12,31,B6,745,2359,-4.0
5819076,JFK,SJU,2015,12,31,B6,1503,2359,-9.0
5819077,MCO,SJU,2015,12,31,B6,333,2359,-6.0
5819078,JFK,BQN,2015,12,31,B6,839,2359,15.0

In [12]:
# In order to ensure the quality of data, we are going to look for outliers, missing values or absurd values. 
flights_datafr_clean.describe()

,YEAR,MONTH,DAY,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY
count,5819079.0,5.819079e+06,5.819079e+06,5.819079e+06,5.819079e+06,5.732926e+06
mean,2015.0,6.524085e+00,1.570459e+01,2.173093e+03,1.329602e+03,9.370158e+00
std,0.0,3.405137e+00,8.783425e+00,1.757064e+03,4.837518e+02,3.708094e+01
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.200000e+01
25%,2015.0,4.000000e+00,8.000000e+00,7.300000e+02,9.170000e+02,-5.000000e+00
50%,2015.0,7.000000e+00,1.600000e+01,1.690000e+03,1.325000e+03,-2.000000e+00
75%,2015.0,9.000000e+00,2.300000e+01,3.230000e+03,1.730000e+03,7.000000e+00
max,2015.0,1.200000e+01,3.100000e+01,9.855000e+03,2.359000e+03,1.988000e+03

In [15]:
flights_datafr_clean.shape[0] - int(flights_datafr_clean['DEPARTURE_DELAY'].count())
# Looking at the table above, we can see that there are 86153 observations with null values.

86153

In [18]:
# Next, we are going to remove these rows
flights_datafr_cleaned = flights_datafr_clean.dropna(axis= 0, how= 'any')
flights_datafr_cleaned.describe()
# The result after applying "dropna" is a table without null values and with 5732926 observations.

,YEAR,MONTH,DAY,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY
count,5732926.0,5.732926e+06,5.732926e+06,5.732926e+06,5.732926e+06,5.732926e+06
mean,2015.0,6.547211e+00,1.570853e+01,2.165226e+03,1.328964e+03,9.370158e+00
std,0.0,3.397111e+00,8.774777e+00,1.755119e+03,4.834728e+02,3.708094e+01
min,2015.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-8.200000e+01
25%,2015.0,4.000000e+00,8.000000e+00,7.280000e+02,9.160000e+02,-5.000000e+00
50%,2015.0,7.000000e+00,1.600000e+01,1.681000e+03,1.325000e+03,-2.000000e+00
75%,2015.0,9.000000e+00,2.300000e+01,3.213000e+03,1.730000e+03,7.000000e+00
max,2015.0,1.200000e+01,3.100000e+01,9.794000e+03,2.359000e+03,1.988000e+03

In [19]:
len((flights_datafr_cleaned['DESTINATION_AIRPORT'].unique()))
# Using the code above, we realize that there are 930 different destinations. For our analysis, we are only going to use
# the following :
# BOS, JFK, SFO AND LAX

930

In [21]:
# The code below, it's used to filter the following dimensions:
# 'DESTINATION_AIRPORT'.- we are only going to analyse the airports ['BOS', 'JFK', 'SFO', 'LAX']
# 'DEPARTURE_DELAY' is a measure with a mean of 9.37 and a median of -2 . It means that there are outliers to the right and
# the values are right-skewed. We filter out values that have more than 1440 minutes of delay.

flights_datafr_cleaned = flights_datafr_cleaned[lambda x : (x['ORIGIN_AIRPORT'].isin(['BOS', 'JFK', 'SFO', 'LAX'])) & 
                                    (x['DEPARTURE_DELAY'] < 24*60)]
flights_datafr_cleaned.describe()

,YEAR,MONTH,DAY,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY
count,535744.0,535744.000000,535744.000000,535744.000000,535744.000000,535744.000000
mean,2015.0,6.252133,15.705572,1716.287624,1335.677180,10.847399
std,0.0,3.360082,8.770304,1722.340144,515.500947,37.724875
min,2015.0,1.000000,1.000000,1.000000,1.000000,-38.000000
25%,2015.0,3.000000,8.000000,454.000000,900.000000,-5.000000
50%,2015.0,6.000000,16.000000,1140.000000,1310.000000,-1.000000
75%,2015.0,9.000000,23.000000,2278.000000,1739.000000,9.000000
max,2015.0,12.000000,31.000000,6875.000000,2359.000000,1429.000000

In [24]:
# The result is a table with 535430 observations where the maximum value of the dimension 'DEPARTURE DELAY' is 1433 minutes
# which is correct.

In [26]:
# Before continuing the analysis, we need to create a new column which merges 4 columns YEAR, MONTH, DAY and SCHEDULED_DEPARTURE.

def convert_to_timedate(x, col='SCHEDULED_DEPARTURE'):
    'Converts to timestamp'
    return (
        pd.to_datetime(
            x['YEAR'].astype(str) + '-' + x['MONTH'].astype(str) + '-' + x['DAY'].astype(str) + 
            ' ' + x.assign(zero='0')['zero']*(4- x[col].astype(str).str.len()) + 
            x[col].astype(str), format= '%Y-%m-%d %H%M', errors = 'coerce'
        )
    )

In [28]:
# The code below, it transforms the dimension 'FLIGHT_NUMBER' to the datatype 'string' and using the function 'convert_to_timedate',
# it merges 4 columns (YEAR, MONTH, DAY, SCHEDULED_DEPARTURE) and return a value DATETIME. 

flights_datafr_cleaned = flights_datafr_cleaned.assign(FLIGHT_NUMBER = lambda x: x['FLIGHT_NUMBER'].astype(str),
                             SCHEDULED_DEPARTURE = lambda x: convert_to_timedate(x),
                             is_delayed= lambda x: np.select(
                                 [x['DEPARTURE_DELAY'] >= 15], [1],
                                 default= 0
                             )
                        )

In [29]:
display(flights_datafr_cleaned)

,ORIGIN_AIRPORT,DESTINATION_AIRPORT,YEAR,MONTH,DAY,AIRLINE,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY,is_delayed
1,LAX,PBI,2015,1,1,AA,2336,2015-01-01 00:10:00,-8.0,0
2,SFO,CLT,2015,1,1,US,840,2015-01-01 00:20:00,-2.0,0
3,LAX,MIA,2015,1,1,AA,258,2015-01-01 00:20:00,-5.0,0
5,SFO,MSP,2015,1,1,DL,806,2015-01-01 00:25:00,-5.0,0
7,LAX,CLT,2015,1,1,US,2013,2015-01-01 00:30:00,14.0,0
...,...,...,...,...,...,...,...,...,...,...
5819068,LAX,ORD,2015,12,31,AA,219,2015-12-31 23:59:00,-1.0,0
5819074,LAX,BOS,2015,12,31,B6,688,2015-12-31 23:59:00,-4.0,0
5819075,JFK,PSE,2015,12,31,B6,745,2015-12-31 23:59:00,-4.0,0
5819076,JFK,SJU,2015,12,31,B6,1503,2015-12-31 23:59:00,-9.0,0
5819078,JFK,BQN,2015,12,31,B6,839,2015-12-31 23:59:00,15.0,1

In [32]:
# As we already used the columns YEAR, MONTH and DAY; These columns are deleted.
flights_datafr_cleaned = flights_datafr_cleaned.drop(['YEAR', 'MONTH', 'DAY'], axis= 1)
display(flights_datafr_cleaned)

,ORIGIN_AIRPORT,DESTINATION_AIRPORT,AIRLINE,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY,is_delayed
1,LAX,PBI,AA,2336,2015-01-01 00:10:00,-8.0,0
2,SFO,CLT,US,840,2015-01-01 00:20:00,-2.0,0
3,LAX,MIA,AA,258,2015-01-01 00:20:00,-5.0,0
5,SFO,MSP,DL,806,2015-01-01 00:25:00,-5.0,0
7,LAX,CLT,US,2013,2015-01-01 00:30:00,14.0,0
...,...,...,...,...,...,...,...
5819068,LAX,ORD,AA,219,2015-12-31 23:59:00,-1.0,0
5819074,LAX,BOS,B6,688,2015-12-31 23:59:00,-4.0,0
5819075,JFK,PSE,B6,745,2015-12-31 23:59:00,-4.0,0
5819076,JFK,SJU,B6,1503,2015-12-31 23:59:00,-9.0,0
5819078,JFK,BQN,B6,839,2015-12-31 23:59:00,15.0,1

In [34]:
flights_datafr_cleaned.describe()

                 SCHEDULED_DEPARTURE  DEPARTURE_DELAY     is_delayed
count                         535744    535744.000000  535744.000000
mean   2015-06-24 04:30:47.153304576        10.847399       0.205292
min              2015-01-01 00:10:00       -38.000000       0.000000
25%              2015-03-30 13:25:00        -5.000000       0.000000
50%              2015-06-20 06:39:00        -1.000000       0.000000
75%              2015-09-06 13:05:00         9.000000       0.000000
max              2015-12-31 23:59:00      1429.000000       1.000000
std                              NaN        37.724875       0.403915

In [36]:
# From the summary above, the dataset has been reduced to 535430 observations. 
# Also, the problem of the missing values has been solved and the column 'is_delayed' gives away that roughly 22% of
# flights have a delay.

## Joining information from different sources

In [39]:
# We want to obtain the name of the arrival airport from the CSV archive 'airports_datafr_raw'.
# The name of the airport has to be added to the dataframe 'flights_datafr_cleaned'.

# First, let's go to check out the dataframe 'airports_datafr_raw'.

airports_datafr_raw.head()

,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,ABE,Lehigh Valley International Airport,Allentown,PA,USA,40.65236,-75.44040
1,ABI,Abilene Regional Airport,Abilene,TX,USA,32.41132,-99.68190
2,ABQ,Albuquerque International Sunport,Albuquerque,NM,USA,35.04022,-106.60919
3,ABR,Aberdeen Regional Airport,Aberdeen,SD,USA,45.44906,-98.42183
4,ABY,Southwest Georgia Regional Airport,Albany,GA,USA,31.53552,-84.19447

In [41]:
flights_airports_merge = flights_datafr_cleaned.merge(airports_datafr_raw, left_on= 'ORIGIN_AIRPORT', right_on= 'IATA_CODE')

In [43]:
# With the code above, 2 datasets have been joined using a column in commun called 'ORIGIN_AIRPORT' and 'IATA_CODE'.

In [45]:
flights_airports_merge

,ORIGIN_AIRPORT,DESTINATION_AIRPORT,AIRLINE,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY,is_delayed,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,LAX,PBI,AA,2336,2015-01-01 00:10:00,-8.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
1,LAX,MIA,AA,258,2015-01-01 00:20:00,-5.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
2,LAX,CLT,US,2013,2015-01-01 00:30:00,14.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
3,LAX,MSP,DL,1434,2015-01-01 00:35:00,0.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
4,LAX,MIA,AA,115,2015-01-01 01:05:00,-2.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535739,JFK,BUF,B6,2002,2015-12-31 22:50:00,17.0,1,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535740,JFK,BOS,B6,718,2015-12-31 23:12:00,-5.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535741,JFK,PSE,B6,745,2015-12-31 23:59:00,-4.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535742,JFK,SJU,B6,1503,2015-12-31 23:59:00,-9.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535743,JFK,BQN,B6,839,2015-12-31 23:59:00,15.0,1,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893

## Calculating the number of flights per airport

In [48]:
# The target is calculated the number of departing flights per airport across the year.

In [50]:
flights_per_airport = flights_airports_merge.groupby(['ORIGIN_AIRPORT', 'AIRPORT']).apply(lambda x: pd.Series({'nb_flights' : len(x['FLIGHT_NUMBER'])})).reset_index()
display(flights_per_airport)

,ORIGIN_AIRPORT,AIRPORT,nb_flights
0,BOS,Gen. Edward Lawrence Logan International Airport,105276
1,JFK,John F. Kennedy International Airport (New Yor...,91933
2,LAX,Los Angeles International Airport,192584
3,SFO,San Francisco International Airport,145951

In [52]:
flights_per_airport.assign(percentage_flights=lambda x: ((x['nb_flights'])/sum(x['nb_flights']))*100)
# The result shows that Los Angeles International Airport carries out the majority of flights with approximately 36 %
# followed by San Francisco International Airport with 27 %.

,ORIGIN_AIRPORT,AIRPORT,nb_flights,percentage_flights
0,BOS,Gen. Edward Lawrence Logan International Airport,105276,19.650430
1,JFK,John F. Kennedy International Airport (New Yor...,91933,17.159875
2,LAX,Los Angeles International Airport,192584,35.947019
3,SFO,San Francisco International Airport,145951,27.242676

## Calculating the delayed flights for biggest airlines

In [55]:
# The variable 'biggest airlines' is measured by the number of yearly flights.

In [57]:
delayed_flights_big_airlines = flights_datafr_cleaned.groupby(['AIRLINE']).apply(lambda x: pd.Series({'nb_flights': len(x['FLIGHT_NUMBER']),
                                                                      'perc_delayed': round(np.average(x['is_delayed']), 4)
                                                                      })).reset_index()
display(delayed_flights_big_airlines)
# The result is a dataframe with the following results:
# The column 'nb_flights' has summarized the number de flights per airline.
# The column 'perc_delayed' presents the percentage of flights per airline.

   AIRLINE  nb_flights  perc_delayed
0       AA     77024.0        0.1535
1       AS     14655.0        0.1252
2       B6     85920.0        0.2080
3       DL     73821.0        0.2016
4       EV      2219.0        0.1676
5       F9      3318.0        0.2288
6       HA      2511.0        0.0816
7       MQ      3429.0        0.2426
8       NK      6475.0        0.3158
9       OO     70748.0        0.2091
10      UA     86562.0        0.2327
11      US     16047.0        0.1445
12      VX     32767.0        0.1730
13      WN     60248.0        0.2728

In [59]:
# We need to range the airlines by the number of flights.
# With the code below , a new column has been created in order to obtain a ranking by the number of flights.

delayed_flights_big_airlines = delayed_flights_big_airlines.assign(rank_size= lambda x: x['nb_flights'].rank(method='first', ascending=False))
display(delayed_flights_big_airlines)

   AIRLINE  nb_flights  perc_delayed  rank_size
0       AA     77024.0        0.1535        3.0
1       AS     14655.0        0.1252        9.0
2       B6     85920.0        0.2080        2.0
3       DL     73821.0        0.2016        4.0
4       EV      2219.0        0.1676       14.0
5       F9      3318.0        0.2288       12.0
6       HA      2511.0        0.0816       13.0
7       MQ      3429.0        0.2426       11.0
8       NK      6475.0        0.3158       10.0
9       OO     70748.0        0.2091        5.0
10      UA     86562.0        0.2327        1.0
11      US     16047.0        0.1445        8.0
12      VX     32767.0        0.1730        7.0
13      WN     60248.0        0.2728        6.0

In [61]:
delayed_flights_big_airlines = delayed_flights_big_airlines[lambda x: x['rank_size']<=10].drop('rank_size', axis = 1)
display(delayed_flights_big_airlines)

# The result of this code has kept the top ten.
# The column rank_size was deleted

   AIRLINE  nb_flights  perc_delayed
0       AA     77024.0        0.1535
1       AS     14655.0        0.1252
2       B6     85920.0        0.2080
3       DL     73821.0        0.2016
8       NK      6475.0        0.3158
9       OO     70748.0        0.2091
10      UA     86562.0        0.2327
11      US     16047.0        0.1445
12      VX     32767.0        0.1730
13      WN     60248.0        0.2728

In [63]:
# The column 'AIRLINE' only shows the code of each airline. 
# We need to add a new column with the full name of each airline.
# Finally, we need to range in descending order based on the column 'nb_flights'.

delayed_flights_big_airlines.merge(airlines_datafr_raw, left_on= 'AIRLINE', right_on= 'IATA_CODE').reset_index(drop=True).sort_values(
                                                                            by = ['perc_delayed'], ascending= False)

  AIRLINE_x  nb_flights  perc_delayed IATA_CODE               AIRLINE_y
4        NK      6475.0        0.3158        NK        Spirit Air Lines
9        WN     60248.0        0.2728        WN  Southwest Airlines Co.
6        UA     86562.0        0.2327        UA   United Air Lines Inc.
5        OO     70748.0        0.2091        OO   Skywest Airlines Inc.
2        B6     85920.0        0.2080        B6         JetBlue Airways
3        DL     73821.0        0.2016        DL    Delta Air Lines Inc.
8        VX     32767.0        0.1730        VX          Virgin America
0        AA     77024.0        0.1535        AA  American Airlines Inc.
7        US     16047.0        0.1445        US         US Airways Inc.
1        AS     14655.0        0.1252        AS    Alaska Airlines Inc.

In [65]:
# The result of the code above shows us that the airline 'Spirit Air Lines' has approximately 31% of delayed flights, 
# followed by the airline 'Southwest Airlines Co.' with 27% and at third place 'United Air Lines Inc.' with 23%.
# On the other hand, Alaska Airlines Inc., US Airways Inc. and American Airlines Inc. have between 12% and 15% of delayed flights.

## Data Frame Transformations

In [68]:
# We want to know the monthly change of flights by origin airport.
# 'flights_airports_merge' is the data frame that would be used.

In [70]:
flights_airports_merge

,ORIGIN_AIRPORT,DESTINATION_AIRPORT,AIRLINE,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY,is_delayed,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,LAX,PBI,AA,2336,2015-01-01 00:10:00,-8.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
1,LAX,MIA,AA,258,2015-01-01 00:20:00,-5.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
2,LAX,CLT,US,2013,2015-01-01 00:30:00,14.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
3,LAX,MSP,DL,1434,2015-01-01 00:35:00,0.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
4,LAX,MIA,AA,115,2015-01-01 01:05:00,-2.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535739,JFK,BUF,B6,2002,2015-12-31 22:50:00,17.0,1,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535740,JFK,BOS,B6,718,2015-12-31 23:12:00,-5.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535741,JFK,PSE,B6,745,2015-12-31 23:59:00,-4.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535742,JFK,SJU,B6,1503,2015-12-31 23:59:00,-9.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535743,JFK,BQN,B6,839,2015-12-31 23:59:00,15.0,1,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893

In [72]:
# From the column 'SCHEDULED_DEPARTURE', we are going to extract the month expressed like the full month name and 
# month number.
flights_airports_add_month= flights_airports_merge.assign(month=lambda x: x['SCHEDULED_DEPARTURE'].dt.strftime('%B'),
                              month_num=lambda x: x['SCHEDULED_DEPARTURE'].dt.strftime('%m').astype(int)
                             )
display(flights_airports_add_month)

,ORIGIN_AIRPORT,DESTINATION_AIRPORT,AIRLINE,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY,is_delayed,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE,month,month_num
0,LAX,PBI,AA,2336,2015-01-01 00:10:00,-8.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,January,1
1,LAX,MIA,AA,258,2015-01-01 00:20:00,-5.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,January,1
2,LAX,CLT,US,2013,2015-01-01 00:30:00,14.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,January,1
3,LAX,MSP,DL,1434,2015-01-01 00:35:00,0.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,January,1
4,LAX,MIA,AA,115,2015-01-01 01:05:00,-2.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807,January,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535739,JFK,BUF,B6,2002,2015-12-31 22:50:00,17.0,1,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893,December,12
535740,JFK,BOS,B6,718,2015-12-31 23:12:00,-5.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893,December,12
535741,JFK,PSE,B6,745,2015-12-31 23:59:00,-4.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893,December,12
535742,JFK,SJU,B6,1503,2015-12-31 23:59:00,-9.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893,December,12
535743,JFK,BQN,B6,839,2015-12-31 23:59:00,15.0,1,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893,December,12

In [73]:
# Using the 'flights_airports_add_month' data frame obtained lines above, we are going to summarize the number of flights
# by 'ORIGIN_AIRPORT', 'month' and 'month_num'.
summarize_flights_airport_by_month = flights_airports_add_month.groupby(['ORIGIN_AIRPORT', 'month','month_num']).apply(lambda x: pd.Series(
                                    {'nb_flights': len(x['FLIGHT_NUMBER'])})).reset_index().sort_values(['ORIGIN_AIRPORT','month_num']
                                                                                                       ).reset_index(drop=True)
display(summarize_flights_airport_by_month)

   ORIGIN_AIRPORT      month  month_num  nb_flights
0             BOS    January          1        8201
1             BOS   February          2        7251
2             BOS      March          3        9744
3             BOS      April          4        9940
4             BOS        May          5       10172
5             BOS       June          6       10405
6             BOS       July          7       10765
7             BOS     August          8       10644
8             BOS  September          9        9685
9             BOS   November         11        9422
10            BOS   December         12        9047
11            JFK    January          1        7999
12            JFK   February          2        7271
13            JFK      March          3        8451
14            JFK      April          4        8497
15            JFK        May          5        8802
16            JFK       June          6        8745
17            JFK       July          7        9152
18            JFK     August          8        9124
19            JFK  September          9        8000
20            JFK   November         11        7699
21            JFK   December         12        8193
22            LAX    January          1       17097
23            LAX   February          2       15441
24            LAX      March          3       17842
25            LAX      April          4       17307
26            LAX        May          5       17883
27            LAX       June          6       18262
28            LAX       July          7       19097
29            LAX     August          8       19034
30            LAX  September          9       17399
31            LAX   November         11       16365
32            LAX   December         12       16857
33            SFO    January          1       12614
34            SFO   February          2       11229
35            SFO      March          3       13274
36            SFO      April          4       12906
37            SFO        May          5       13411
38            SFO       June          6       13612
39            SFO       July          7       14277
40            SFO     August          8       14446
41            SFO  September          9       13262
42            SFO   November         11       13454
43            SFO   December         12       13466

In [76]:
# Next, we want to compare the number of flights carries out over the current month against the month before.

summarize_flights_airport_by_month= summarize_flights_airport_by_month.assign(nb_flights_before= lambda x: x.groupby(['ORIGIN_AIRPORT'])['nb_flights'].shift(1),
                                          perc_chance=lambda x: round((x['nb_flights']- x['nb_flights_before'])/x['nb_flights_before'], 2)
                                         ).drop(['month_num'], axis = 1)
display(summarize_flights_airport_by_month)

   ORIGIN_AIRPORT      month  nb_flights  nb_flights_before  perc_chance
0             BOS    January        8201                NaN          NaN
1             BOS   February        7251             8201.0        -0.12
2             BOS      March        9744             7251.0         0.34
3             BOS      April        9940             9744.0         0.02
4             BOS        May       10172             9940.0         0.02
5             BOS       June       10405            10172.0         0.02
6             BOS       July       10765            10405.0         0.03
7             BOS     August       10644            10765.0        -0.01
8             BOS  September        9685            10644.0        -0.09
9             BOS   November        9422             9685.0        -0.03
10            BOS   December        9047             9422.0        -0.04
11            JFK    January        7999                NaN          NaN
12            JFK   February        7271             7999.0        -0.09
13            JFK      March        8451             7271.0         0.16
14            JFK      April        8497             8451.0         0.01
15            JFK        May        8802             8497.0         0.04
16            JFK       June        8745             8802.0        -0.01
17            JFK       July        9152             8745.0         0.05
18            JFK     August        9124             9152.0        -0.00
19            JFK  September        8000             9124.0        -0.12
20            JFK   November        7699             8000.0        -0.04
21            JFK   December        8193             7699.0         0.06
22            LAX    January       17097                NaN          NaN
23            LAX   February       15441            17097.0        -0.10
24            LAX      March       17842            15441.0         0.16
25            LAX      April       17307            17842.0        -0.03
26            LAX        May       17883            17307.0         0.03
27            LAX       June       18262            17883.0         0.02
28            LAX       July       19097            18262.0         0.05
29            LAX     August       19034            19097.0        -0.00
30            LAX  September       17399            19034.0        -0.09
31            LAX   November       16365            17399.0        -0.06
32            LAX   December       16857            16365.0         0.03
33            SFO    January       12614                NaN          NaN
34            SFO   February       11229            12614.0        -0.11
35            SFO      March       13274            11229.0         0.18
36            SFO      April       12906            13274.0        -0.03
37            SFO        May       13411            12906.0         0.04
38            SFO       June       13612            13411.0         0.01
39            SFO       July       14277            13612.0         0.05
40            SFO     August       14446            14277.0         0.01
41            SFO  September       13262            14446.0        -0.08
42            SFO   November       13454            13262.0         0.01
43            SFO   December       13466            13454.0         0.00

## Most popular routes by origin airport

In [79]:
# We are interested in knowing the top 3 routes per origin airport. 
# A top route from an airport is one with the highest number of flights departing from that airport.
# We use the data frame called 'flights_airports_merge'.
display(flights_airports_merge)

,ORIGIN_AIRPORT,DESTINATION_AIRPORT,AIRLINE,FLIGHT_NUMBER,SCHEDULED_DEPARTURE,DEPARTURE_DELAY,is_delayed,IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE
0,LAX,PBI,AA,2336,2015-01-01 00:10:00,-8.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
1,LAX,MIA,AA,258,2015-01-01 00:20:00,-5.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
2,LAX,CLT,US,2013,2015-01-01 00:30:00,14.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
3,LAX,MSP,DL,1434,2015-01-01 00:35:00,0.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
4,LAX,MIA,AA,115,2015-01-01 01:05:00,-2.0,0,LAX,Los Angeles International Airport,Los Angeles,CA,USA,33.94254,-118.40807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535739,JFK,BUF,B6,2002,2015-12-31 22:50:00,17.0,1,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535740,JFK,BOS,B6,718,2015-12-31 23:12:00,-5.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535741,JFK,PSE,B6,745,2015-12-31 23:59:00,-4.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535742,JFK,SJU,B6,1503,2015-12-31 23:59:00,-9.0,0,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893
535743,JFK,BQN,B6,839,2015-12-31 23:59:00,15.0,1,JFK,John F. Kennedy International Airport (New Yor...,New York,NY,USA,40.63975,-73.77893

In [85]:
# The next code carries out the count of the flight number by origin airport and destination airport.
Most_popular_routes = flights_airports_merge.groupby(['ORIGIN_AIRPORT','DESTINATION_AIRPORT']).apply(
                       lambda x: pd.Series({'nb_flights': len(x['FLIGHT_NUMBER'])})).reset_index()
display(Most_popular_routes)

    ORIGIN_AIRPORT DESTINATION_AIRPORT  nb_flights
0              BOS                 ACK         118
1              BOS                 ACY         181
2              BOS                 ATL        4603
3              BOS                 AUS         397
4              BOS                 BNA         621
..             ...                 ...         ...
281            SFO                 SNA        4215
282            SFO                 STL         880
283            SFO                 SUN         166
284            SFO                 TUS         646
285            SFO                 XNA          51

[286 rows x 3 columns]

In [103]:
Most_popular_routes = Most_popular_routes.assign(rank_popular = lambda x: x.groupby(['ORIGIN_AIRPORT'])['nb_flights'].rank(method='first',
                                                                                                    ascending=False)
                          )[lambda x: x['rank_popular'] <= 3].reset_index(drop=True).drop(['nb_flights'], axis=1).assign(
    rank_popular= lambda x: 'Top' + x['rank_popular'].astype(int).map(str))
display(Most_popular_routes)
# The code above, it has ordered in descending order each category of 'ORIGIN_AIRPORT' by the number of flights.
# After that, the result has been filtered, taking in count the top 3 by origin airport.
# Finally, a new column called 'rank_popular has been added' which shows the word 'Top' plus the ranking position by 'origin airport'

   ORIGIN_AIRPORT DESTINATION_AIRPORT rank_popular
0             BOS                 DCA         Top1
1             BOS                 LGA         Top2
2             BOS                 ORD         Top3
3             JFK                 LAX         Top1
4             JFK                 MCO         Top3
5             JFK                 SFO         Top2
6             LAX                 JFK         Top2
7             LAX                 LAS         Top3
8             LAX                 SFO         Top1
9             SFO                 JFK         Top2
10            SFO                 LAS         Top3
11            SFO                 LAX         Top1

In [111]:
Most_popular_routes.pivot_table(
    columns='rank_popular',
    values= 'DESTINATION_AIRPORT',
    index= 'ORIGIN_AIRPORT',
    aggfunc= np.sum
).rename_axis(None, axis=1).reset_index()
# The code above, we used the function pivot table to reorder the data frame. Finally, we obtain a table where 
# we can oberve more clearly the top 3 by origin airport.

C:\Users\TCAMELIDOSARQ6\AppData\Local\Temp\ipykernel_23732\3868292410.py:1: FutureWarning: The provided callable <function sum at 0x00000214942ADBC0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  Most_popular_routes.pivot_table(

  ORIGIN_AIRPORT Top1 Top2 Top3
0            BOS  DCA  LGA  ORD
1            JFK  LAX  SFO  MCO
2            LAX  SFO  JFK  LAS
3            SFO  LAX  JFK  LAS